/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReservarRouteImport } from './routes/reservar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InstructorRouteImport } from './routes/instructor'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSmsSendRouteImport } from './routes/api.sms.send'
import { Route as ApiDniDniRouteImport } from './routes/api.dni.$dni'

const ReservarRoute = ReservarRouteImport.update({
  id: '/reservar',
  path: '/reservar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorRoute = InstructorRouteImport.update({
  id: '/instructor',
  path: '/instructor',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSmsSendRoute = ApiSmsSendRouteImport.update({
  id: '/api/sms/send',
  path: '/api/sms/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDniDniRoute = ApiDniDniRouteImport.update({
  id: '/api/dni/$dni',
  path: '/api/dni/$dni',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/instructor': typeof InstructorRoute
  '/login': typeof LoginRoute
  '/reservar': typeof ReservarRoute
  '/api/dni/$dni': typeof ApiDniDniRoute
  '/api/sms/send': typeof ApiSmsSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/instructor': typeof InstructorRoute
  '/login': typeof LoginRoute
  '/reservar': typeof ReservarRoute
  '/api/dni/$dni': typeof ApiDniDniRoute
  '/api/sms/send': typeof ApiSmsSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/instructor': typeof InstructorRoute
  '/login': typeof LoginRoute
  '/reservar': typeof ReservarRoute
  '/api/dni/$dni': typeof ApiDniDniRoute
  '/api/sms/send': typeof ApiSmsSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/instructor'
    | '/login'
    | '/reservar'
    | '/api/dni/$dni'
    | '/api/sms/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/instructor'
    | '/login'
    | '/reservar'
    | '/api/dni/$dni'
    | '/api/sms/send'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/instructor'
    | '/login'
    | '/reservar'
    | '/api/dni/$dni'
    | '/api/sms/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  InstructorRoute: typeof InstructorRoute
  LoginRoute: typeof LoginRoute
  ReservarRoute: typeof ReservarRoute
  ApiDniDniRoute: typeof ApiDniDniRoute
  ApiSmsSendRoute: typeof ApiSmsSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reservar': {
      id: '/reservar'
      path: '/reservar'
      fullPath: '/reservar'
      preLoaderRoute: typeof ReservarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor': {
      id: '/instructor'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof InstructorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sms/send': {
      id: '/api/sms/send'
      path: '/api/sms/send'
      fullPath: '/api/sms/send'
      preLoaderRoute: typeof ApiSmsSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dni/$dni': {
      id: '/api/dni/$dni'
      path: '/api/dni/$dni'
      fullPath: '/api/dni/$dni'
      preLoaderRoute: typeof ApiDniDniRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  InstructorRoute: InstructorRoute,
  LoginRoute: LoginRoute,
  ReservarRoute: ReservarRoute,
  ApiDniDniRoute: ApiDniDniRoute,
  ApiSmsSendRoute: ApiSmsSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
